server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/movie_chart?serverTimezone=Asia/Seoul
    username: root
    password: toor
    
  security:
    user:
      name: test
      password: 1234   
    oauth2:
      client:
        registration:
          google:
            client-id:  515866456923-08o20debecpgpm0sp5ggu0neqt95vl8k.apps.googleusercontent.com  #부여받은것
            client-secret:  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    #부여받은것
            scope:
            - email
            - profile
          facebook:
            client-id: 410166104185568
            client-secret: 19129b59ce9b36b68c631ddc80903d44
            scope:
            - email
            - public_profile
          naver:
            client-id: 0kztogdqL2gmO0BO1g2L
            client-secret: hLcU7lqx7s
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri:  https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 JSON형태로 가지고 올때 response라는 key값으로 데이터를 전달해 준다.
            
mybatis:
  mapper-locations:
  - /mappers/*.xml